#!/bin/sh

#
# Read all the data available from a FIFO as a series of separate open+reads
#

if [ $# -ne 1 ]
then
    echo "Need the name of the FIFO to read from" >&2
    exit -1
fi

# give the FIFO value a better name
fifo=$1

if [ ! -p $fifo ]; then
    echo "The FIFO ${fifo} doesn't exist - is a writing running?"
    exit 1
fi

read line < $fifo
echo "Command on processor: $line"
exec $line >> commands.log
echo "Reader exiting"
