#!/bin/sh

LOG_P="/tmp/processor-${USER}.log"
#
# Read all the data available from a FIFO as a series of separate open+reads
#

fifo=$1
log=$2
core=$3

while read line < $fifo
do
    if [ "$line" = 'quit' ]
    then
        echo "PROCESSOR : $fifo OFFLINE."
        # leave the while loop
        break
    else
        echo "Command on $fifo: $line"
        (exec echo "`date`" >> $log)
        (exec echo "PID : $core" >> $log)
        (exec echo "COMMAND : $line" >> $log)
        (exec echo "OUTPUT..." >> $log)
        (exec $line >> $log)
        (exec echo "----------" >> $log)
    fi
done