#!/bin/sh

LOG_P="/tmp/processor-${USER}.log"
#
# Read all the data available from a FIFO as a series of separate open+reads
#

fifo=$1
log=$2
core=$3

while read line < $fifo
do
    if [ "$line" = 'quit' ]
    then
        echo "Processor $core exiting"
        # leave the while loop
        break
    else
        echo "Command on $fifo: $line"
        ( echo "PROCESSOR ID: $core" >> $log )
        ( echo "COMMAND: $line" >> $log )
        ( echo "TIME: `date`" >> $log )
        ( echo "OUTPUT:" >> $log )
        ( exec $line >> $log )
        (echo "----------" >> $log)
    fi
done