#!/usr/bin/env python2

import socket
import getpass
import sys
import os

if len(sys.argv) != 2:
    print >> sys.stderr, sys.argv[0], "takes exactly one argument - the FIFO"
    sys.exit(-1)

# record the name of the FIFO we echo everything to
FIFO_NAME = sys.argv[1]

# set up the name of the socket that we want to use
FILE_ADDRESS = "/tmp/server-%s-sock" % getpass.getuser()



# create socket of type AF_UNIX



# bind and listen for incoming connections




# process connections as they come in



